### ISSUE TITLE
redland fails to build on 32 bit architecture using gcc 4.9.3 toolchain

### ISSUE THREAD

**Issue by jimhester** [ropensci/redland-bindings#43]
Relevant error message is

```
../windows/redland-1.0.17/lib/i386/librasqal.a(timegm.o):timegm.c:(.text+0x47): undefined reference to `_mkgmtime'
collect2.exe: error: ld returned 1 exit status
```
An example install failure is at https://www.statistik.tu-dortmund.de/~ligges/3.3new/redland.Rcheck/. I confirmed the error on my windows machine.

The library probably just needs to be rebuilt using the new toolchain

cc @jeroenooms

**Comment by jeroenooms** [comment]
OK I'm on it

**Comment by jeroenooms** [comment]
Uhoh this is actually a bug in mingw-w64: https://sourceforge.net/p/mingw-w64/bugs/473/

**Comment by jeroenooms** [comment]
Bug report: https://github.com/Alexpux/MINGW-packages/issues/1315

**Comment by jeroenooms** [comment]
Here is a temporary workaround: https://github.com/ropensci/redland-bindings/pull/44

**Comment by sbpcs59** [comment]
@jeroenooms I tested the fix with R 3.3.0 beta 32 bit (and other builds) and everything looks
good. Thanks!

**Comment by sbpcs59** [comment]
I verified the update to this issue (https://github.com/ropensci/redland-bindings/pull/47) - the
required library (-lmsvcr100) now only shows up on the link line when building on Windows R 3.3.0
i386 (uses the gcc 4.9.3)
